# Site Settings
title: PortEXE
email: zackazt@gmail.com
description: Technology Explained Casually
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.portexe.com" # the base hostname & protocol for your site
google_analytics: "UA-109849250-1"
author_image: "/zwilson.jpg"
image: "https://i.imgur.com/OM50wrX.png"
image_sm: "https://i.imgur.com/OM50wrX.png"
image_fb: "https://i.imgur.com/4e3C70Y.jpg"

# User Settings
username: PortEXE - Technology Explained Casually
user_description: Websites, Apps, and Technology Explained Casually.
disqus_username: zwilsondev-com

# Social Media
# Remove the item if you don't need it
github_username: zackazt
twitter_username: portexe
#instagram_username: port.exe
youtube_username: channel/UCjGQyJCSU_VVMTu5nigonqg
facebook_username: Portexe-2123922254496260
#twitch_username: portexe
#patreon_username: portexe

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
