# Site Settings
title: TheZackAZT - Web and App Developer
email: zackazt@gmail.com
description: Websites, Apps, and Technology Explained Casually.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.zackazt.com" # the base hostname & protocol for your site
google_analytics: "UA-109849250-1"
author_image: "/zwilson.jpg"
image: "https://i.imgur.com/iTdx3bV.png"
image_sm: "https://i.imgur.com/TLvihxr.png"
image_fb: "https://i.imgur.com/5LLBvP7.png"

# User Settings
username: ZackAZT - Tech Explained Casually
user_description: Websites, Apps, and Technology Explained Casually.
disqus_username: zwilsondev-com

# Social Media
# Remove the item if you don't need it
github_username: zackazt
twitter_username: TheZackAZT
instagram_username: zackazt
linkedin_username: zackazt
facebook_username: TheZackazt

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
